#!/bin/sh

# Check asterisk channels for length > 9:59:59 plugin for Nagios.
# Original Written by Chad Phillips (chad@apartmentlines.com)
# Modified by Bryan Nelson for length check (bnelson@fluentstream.com)
# Last Modified: 2013-08-06


PROGPATH=`dirname $0`
REVISION=`echo '$Revision: 1 $' | sed -e 's/[^0-9.]//g'`
DATETIME=`date "+%Y-%m-%d %H:%M:%S"`
TAB="	"

#. $PROGPATH/utils.sh

print_usage() {
    echo "
Usage: check_asterisk_locked_channels [-w <max_channels>] [-c <max_channels>]
Usage: check_asterisk_locked_channels --help | -h

Description:

This plugin checks an asterisk server for locked Channels.
Any channel over 9:59:59 is considered to be in a locked state.

Tested to work on Linux.

The following arguments are accepted:

  -w              (Optional) Generate a warning message if the defined number
                  channels is exceeded.

  -c              (Optional) Generate a critical message if the defined number
                  channels is exceeded.

  --help | -h     Print this help and exit.

Examples:

Check channels for anything over 9:59:59, with no concern about limits.

  check_asterisk_locked_channels

Check channels/calls.  Issue a warning if there is more than 1 'locked'
channel, and a critical if there are more than 3 'locked' channels.

  check_asterisk_locked_channels -w 1 -c 3
"
}

print_help() {
    print_usage
    echo "Check asterisk locked channels plugin for Nagios."
    echo ""
}

# Sets the exit status for the plugin.  This is done in such a way that the
# status can only go in one direction: OK -> WARNING -> CRITICAL.
set_exit_status() {
	new_status=$1
	# Nothing needs to be done if the state is already critical, so exclude
	# that case.
	case $exitstatus
	in
		$STATE_WARNING)
			# Only upgrade from warning to critical.
			if [ "$new_status" = "$STATE_CRITICAL" ]; then
				exitstatus=$new_status;
			fi
		;;
		$STATE_OK)
			# Always update state if current state is OK.
			exitstatus=$new_status;
		;;
	esac
}

# Ensures that a call to the Asterisk process returns successfully.  Exits
# critical if not.
check_asterisk_result() {
	if [ "$1" != "0" ]; then
		echo "CRITICAL: $2"
		exit $STATE_CRITICAL
	fi
}

# Defaults.
exitstatus=$STATE_OK
lockchan_warning=-1
lockchan_critical=-1


# Grab the command line arguments.
while test -n "$1"; do
    case "$1" in
        --help)
            print_help
            exit $STATE_OK
            ;;
        -h)
            print_help
            exit $STATE_OK
            ;;
        -w)
            lockchan_warning=$2
            shift
            ;;
        -c)
            lockchan_critical=$2
            shift
            ;;
        -x)
            exitstatus=$2
            shift
            ;;
        --exitstatus)
            exitstatus=$2
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            print_usage
            exit $STATE_UNKNOWN
            ;;
    esac
    shift
done

# Sanity checking for arguments.
if [ "$lockchan_warning" != "-1" ] && ([ ! "$lockchan_warning" ] || [ `echo "$lockchan_warning" | grep [^0-9]` ]); then
	echo "Number of channels warning value must be a number."
	exit $STATE_UNKNOWN
fi

if [ "$lockchan_critical" != "-1" ] && ([ ! "$lockchan_critical" ] || [ `echo "$lockchan_critical" | grep [^0-9]` ]); then
	echo "Number of channels critical value must be a number."
	exit $STATE_UNKNOWN
fi

if [ "$lockchan_warning" != "-1" ] && [ "$lockchan_critical" != "-1" ] && [ "$lockchan_warning" -ge "$lockchan_critical" ]; then
	echo "Critical channels must be greater than warning channels."
	exit $STATE_UNKNOWN
fi


# Fetch the data from asterisk.
command_output=`asterisk -rx "core show channels verbose"`
#echo "$command_output"
# Parse the data.
lockchan_count=`echo "$command_output"|grep '[1-9][0-9]:[0-9][0-9]:[0-9][0-9]' | wc -l`
lockchan_fullline=`echo "$command_output"|grep '[1-9][0-9]:[0-9][0-9]:[0-9][0-9]'`
#echo "$lockchan_count"
#echo "$lockchan_fullline"
# Test for warning/critical channels.
if [ "$lockchan_critical" != "-1" ] && [ "$lockchan_count" -gt "$lockchan_critical" ]; then
	set_exit_status $STATE_CRITICAL
elif [ "$lockchan_warning" != "-1" ] && [ "$lockchan_count" -gt "$lockchan_warning" ]; then
	set_exit_status $STATE_WARNING
elif [ "$lockchan_count" != "0" ]; then
        set_exit_status $STATE_OK
fi


case $exitstatus
in
	$STATE_CRITICAL)
		exit_message="CRITICAL";
	;;
	$STATE_WARNING)
		exit_message="WARNING";
	;;
	$STATE_OK)
		exit_message="OK";
	;;
	*)
		echo "UNKNOWN"
		exit $STATE_UNKNOWN;
		
	;;
esac

echo "${exit_message}: $lockchan_count Locked Channels, | ${DATETIME}";

exit $exitstatus

